### ISSUE TITLE
Isabelle review Tasks + Solutions reviewing

### ISSUE THREAD

**Issue by ckcollab** [codalab/competitions-v2#150]
## Where to test
http://134.158.74.47/

Login admin//admin

Then in the top right you can access the management screens..

<img src="https://user-images.githubusercontent.com/2185159/53854188-46a21500-3f7d-11e9-8a9b-98f02263b7bf.png" width="200px">

a. manage competitions
b. manage tasks (and view their solutions)

From a competition detail page, you can make submission uploads by clicking this input:
![image](https://user-images.githubusercontent.com/2185159/53854290-c334f380-3f7d-11e9-8c73-33dd966d4d6f.png)

### Testing tasks and solutions

- [ ] can upload a "tasks + solutions" competition, for example [Pisano Period](https://github.com/codalab/competition-examples/tree/master/v2/pisano_period)
- [x] no longer required to zip up ingestion program, scoring program, etc. can just reference the directory and it is zipped during competition unpacking
- [x] should see submission output streaming as you make the submission
- [ ] should be able to manage/edit your own tasks
- [ ] Should be able to see a list of PUBLIC tasks and their solutions
- [ ] Making multiple submissions shows the modal each time ~*(currently broken, only shows modal properly for first submission made)*~
- [ ] 10gb upload works

### Selenium automated tests

- [x] Creating submission
- [x] Creating competition via bundle upload
- [x] Login
- [x] Runs on CircleCI before every deploy confirming the "full loop" of the site (competition creation, submission processing)

### Testing dumps

- [x] Be able to dump and re-upload a competitions without errors
  - [ ] Test against multiple test competitions

**Comment by madclam** [comment]
I have been doing some testing, here is some feed-back:

UI:
Top of screen: big header vertically, save real estate space vertically. See the layout of https://autodl.lri.fr/competitions/118. Also display the same information.
Participants should be able to easily download the solution.
Phases: missing information. See e.g. https://autodl.lri.fr/competitions/118#phases

YAML:
Where does the "Welcome" page end up?
Where are the pages "Overview", "terms and Conditions", "FAQ" specified?
We need an example with input data and reference data
How would an example with multiple tasks and solutions look like?
Explain the syntax of solutions

SUBMISSIONS:
Green "Upload your submission" button does not work.
Sample submission processed
Cannot download output of scoring step
Nice interface for logs but most are empty, is this normal?

TASKS and SOLUTIONS
Add cancel button for editing panels (all)
Would it be possible to view contents (not just download)?
Unclear how to create a new task from the form, give instructions.
How should we refer tasks from YAML? No keys.

DATASETS
search function really nice
As previously discussed the name "DATASET" is confusing (it includes both data and code)
Should let people make datasets available unless validated. Do not put "public" checkbox in upload form. Put it in dataset table, but only when validated. For a competition bundle, validated means that is passed paper validation. For task it means that it was validated by a solution. For a solution it means that it was validated by a task. Not sure that the other types of "datasets" should be made public ever.
Would be better to have exact date/time of upload.
View description.
Can we view without downloading?
Need to know whether a given dataset is currently in use (or can be safely deleted): give a list of resources that point to it.
Need multi-delete function.
Dumps: competitions can be downloaded from "Mydatasets": how do we know which competitions corresponds to what?
Tasks and solutions: why are they not in "My Datasets"?

EDITOR
Where do the html pages appear.
What is the effect of "Save and Publish" and "Save as draft"?
Phases created do not appear in order. Re-ordering in editor does not work.
Do we have per-phase leaderboards?
How are leaderboards attached to phases?
Could we download the YAML file.

SUBMISSION MANAGER
Does not show submission IDs, score, compute time, date submitted, See: https://autodl.lri.fr/competitions/118#participate
Download CSV: should show all columns (include zip file name).

LEADERBOARD
Does not seem to be showing anything.

ADMIN
Competition management: published/draft change to published/private (not all unpublished competitions are drafts)
Re-run submissions work
No participant management yet

BUNDLES AND DUMPS:
The competition dumps seem to be missing a lot of stuff and not include latest changes made with the editor.
Very difficult to remember how to create a competition dump.
Why do we have md files instead of HTML files?
Phases do not seem to have an order number in the YAML file (which may explain the problem we have in phase ordering).
