### ISSUE TITLE
Cryptic error message in bundle upload

### ISSUE THREAD

**Issue by madclam** [codalab/competitions-v2#417]
<img width="627" alt="Screen Shot 2020-06-08 at 9 53 01 AM" src="https://user-images.githubusercontent.com/7594063/84058348-f7137b80-a96d-11ea-9809-c0f5a7348001.png">

**Comment by Deathn0t** [comment]
A competition bundle is not accepted if the root folder is selected for zip instead of inner files. Hence, it is returning the error shown in the linked image
<img width="592" alt="Screenshot 2020-06-08 at 18 57 35" src="https://user-images.githubusercontent.com/5201978/84058739-edb00080-a9b9-11ea-8a0a-25ebc2d75fa5.png">
